CREATE TABLE IF NOT EXISTS `lab_agv_load_plan` (
    `id`                 BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
    `task_id`            VARCHAR(64)  NOT NULL COMMENT 'AGV任务号/流程executionId',
    `device_id`          VARCHAR(64)  NOT NULL DEFAULT 'AGV-01' COMMENT 'AGV设备编码',
    `load_station`       VARCHAR(64)  NULL COMMENT '装载等待点；NULL表示不限制',
    `expected_count`     INT          NOT NULL COMMENT '当前车次计划装载数',
    `loaded_count`       INT          NOT NULL DEFAULT 0 COMMENT '已确认装上AGV的数量',
    `wave_size`          INT          NOT NULL DEFAULT 2 COMMENT '单次出货窗口数量',
    `current_wave`       INT          NOT NULL DEFAULT 1 COMMENT '当前装载波次',
    `allow_partial_load` BIT(1)       NOT NULL DEFAULT b'0' COMMENT '是否允许不足一个波次继续',
    `agv_waiting`        BIT(1)       NOT NULL DEFAULT b'0' COMMENT 'AGV是否已到等待点',
    `last_agv_station`   VARCHAR(64)  NULL COMMENT '最近一次等待点',
    `orchestration_node_id` VARCHAR(64) NULL COMMENT '等待整个搬运完成的流程节点',
    `current_agv_task_id` VARCHAR(96) NULL COMMENT '当前AGV子任务号',
    `current_agv_operation` VARCHAR(16) NULL COMMENT 'LOAD/MOVE/UNLOAD',
    `task_type`          VARCHAR(32) NULL,
    `plate_type`         VARCHAR(32) NULL,
    `warehouse_callback_url` VARCHAR(255) NULL,
    `status`             VARCHAR(32)  NOT NULL COMMENT 'LOADING/LOAD_COMPLETE/COMPLETED/FAILED/CANCELLED',
    `creator`            VARCHAR(64)  NULL,
    `updater`            VARCHAR(64)  NULL,
    `create_time`        DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `update_time`        DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted`            BIT(1)       NOT NULL DEFAULT b'0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_agv_load_plan_task` (`task_id`),
    KEY `idx_agv_load_plan_status` (`status`)
    ,KEY `idx_agv_load_plan_agv_task` (`current_agv_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AGV车次多轮装载计划';

CREATE TABLE IF NOT EXISTS `lab_agv_load_item` (
    `id`               BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
    `task_id`          VARCHAR(64)  NOT NULL COMMENT 'AGV任务号/流程executionId',
    `sequence_no`      INT          NOT NULL COMMENT '当前车次中的装载顺序',
    `source_slot_id`   VARCHAR(64)  NOT NULL COMMENT '可重复使用的出货位',
    `agv_slot_id`      VARCHAR(64)  NOT NULL COMMENT 'AGV载货位',
    `target_slot_id`   VARCHAR(64)  NOT NULL COMMENT '最终目标位',
    `instance_id`      VARCHAR(64)  NULL COMMENT '实际物料实例ID',
    `container_type`   VARCHAR(64)  NULL COMMENT '容器类型编码，对应 lab_container_type.type_code',
    `wave_no`          INT          NULL COMMENT '装载波次',
    `warehouse_source_location` VARCHAR(64) NULL COMMENT '仓储内部始发位置',
    `step1_json`       JSON         NULL COMMENT 'AGV装载参数',
    `step2_json`       JSON         NULL COMMENT 'AGV移动参数',
    `step3_json`       JSON         NULL COMMENT 'AGV卸载参数',
    `status`           VARCHAR(32)  NOT NULL COMMENT 'WAIT_SOURCE/READY/DISPATCHED/LOADED/COMPLETED',
    `warehouse_request_id` VARCHAR(96) NULL COMMENT '服务端调用仓储的幂等请求号',
    `ready_request_id` VARCHAR(64)  NULL COMMENT '上游就绪事件幂等号',
    `ready_at`         DATETIME(3)  NULL,
    `dispatched_at`    DATETIME(3)  NULL,
    `loaded_at`        DATETIME(3)  NULL,
    `creator`          VARCHAR(64)  NULL,
    `updater`          VARCHAR(64)  NULL,
    `create_time`      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `update_time`      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted`          BIT(1)       NOT NULL DEFAULT b'0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_agv_load_item_seq` (`task_id`, `sequence_no`),
    UNIQUE KEY `uk_agv_load_item_ready_request` (`ready_request_id`),
    UNIQUE KEY `uk_agv_load_item_warehouse_request` (`warehouse_request_id`),
    KEY `idx_agv_load_item_wait` (`task_id`, `source_slot_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AGV多轮装载物料明细';
