-- 后处理机台事件驱动流程 mock 配置
--
-- 场景：
-- 1. 系统绑定/加载 4 个样本。
-- 2. 查询载具/物料当前位置，组装 AGV startTask 的 command。
-- 3. AGV 搬运到后处理机台。
-- 4. 下发后处理机台任务，机台内部自行扫码。
-- 5. 系统等待机台事件：scanFailed / materialRequired / experimentFinished。
-- 6. 扫码失败：标记样本失败后继续处理剩余样本。
-- 7. 物料不足：查询缺料位置，AGV 补料，通知机台物料到位，再等待最终结果。
-- 8. 实验完成：保存样本结果。

-- ------------------------------------------------------------------
-- 1. AGV 严格报文与后处理机台 mock 指令
-- ------------------------------------------------------------------

DELETE FROM lab_device_command WHERE device_type = 'AGV_MOCK';
DELETE FROM lab_device_command WHERE device_type = 'POST_PROCESSOR_FLOW_MOCK';

INSERT INTO lab_device_command (
    device_type, command_code, completion_mode, request_template, content_type,
    http_method, http_path, timeout_ms, retryable, codec_id,
    poll_path, poll_done_expr, poll_max_times, mock_output, remark,
    creator, updater, create_time, update_time, deleted
) VALUES
(
    'AGV_MOCK',
    'startTask',
    'SYNC',
    '{"taskId":"${taskId}","command":"${command}"}',
    'application/json',
    'POST',
    '/device/agv/startTask',
    120000,
    b'1',
    NULL,
    NULL,
    NULL,
    60,
    '{"code":0,"message":"mock agv startTask accepted"}',
    'AGV 标准接口：控制 AGV 执行任务，报文严格为 taskId + command。',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'AGV_MOCK',
    'startAgain',
    'SYNC',
    '{"taskId":"${taskId}"}',
    'application/json',
    'POST',
    '/device/agv/startAgain',
    30000,
    b'1',
    NULL,
    NULL,
    NULL,
    10,
    '{"code":0,"message":"mock agv startAgain accepted"}',
    'AGV 标准接口：通知 AGV 继续，报文严格为 taskId。',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'POST_PROCESSOR_FLOW_MOCK',
    'startTask',
    'SYNC',
    '{"taskId":"${taskId}","carrierId":"${carrierId}","sampleInfos":"${sampleInfos}","callbackUrl":"${callbackUrl}"}',
    'application/json',
    'POST',
    '/device/post-processor/startTask',
    120000,
    b'1',
    NULL,
    NULL,
    NULL,
    60,
    '{"code":0,"message":"mock post processor task accepted"}',
    '后处理机台启动任务。机台内部扫码，后续通过事件回调推进流程。',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'POST_PROCESSOR_FLOW_MOCK',
    'materialReady',
    'SYNC',
    '{"taskId":"${taskId}","event":"materialReady","materials":"${materials}"}',
    'application/json',
    'POST',
    '/device/post-processor/materialReady',
    30000,
    b'1',
    NULL,
    NULL,
    NULL,
    10,
    '{"code":0,"message":"mock material ready accepted"}',
    '补料完成后通知后处理机台继续。',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
);

-- ------------------------------------------------------------------
-- 2. mock 设备与资源
-- ------------------------------------------------------------------

DELETE FROM lab_device_info WHERE device_id IN ('AGV-MOCK-01', 'POST-PROCESSOR-FLOW-MOCK-01');
INSERT INTO lab_device_info (
    device_id, device_name, device_type, protocol, zone_code,
    host, port, base_url, callback_mode, poll_interval_ms,
    auth_type, auth_config, serial_port, baud_rate, data_bits, stop_bits, parity,
    sdk_class, sdk_config, connect_timeout_ms, read_timeout_ms,
    heartbeat_interval_ms, heartbeat_command, max_concurrent,
    status, enabled, remark,
    creator, updater, create_time, update_time, deleted
) VALUES
(
    'AGV-MOCK-01',
    'AGV Mock 调试车',
    'AGV_MOCK',
    'MOCK',
    'ZONE-A',
    '127.0.0.1',
    0,
    NULL,
    'WEBHOOK',
    NULL,
    'NONE',
    NULL,
    NULL,
    NULL,
    8,
    1,
    'NONE',
    NULL,
    NULL,
    5000,
    30000,
    NULL,
    NULL,
    1,
    'ONLINE',
    b'1',
    '本地 AGV 流程验证专用。',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'POST-PROCESSOR-FLOW-MOCK-01',
    '后处理机台事件流程 Mock',
    'POST_PROCESSOR_FLOW_MOCK',
    'MOCK',
    'ZONE-A',
    '127.0.0.1',
    0,
    NULL,
    'WEBHOOK',
    NULL,
    'NONE',
    NULL,
    NULL,
    NULL,
    8,
    1,
    'NONE',
    NULL,
    NULL,
    5000,
    30000,
    NULL,
    NULL,
    1,
    'ONLINE',
    b'1',
    '后处理机台事件驱动流程 mock 设备。',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
);

DELETE FROM lab_resource_config WHERE resource_id IN ('AGV-MOCK-01', 'POST-PROCESSOR-FLOW-MOCK-01');
INSERT INTO lab_resource_config (
    resource_id, resource_type, ownership_type, zone_code, max_concurrent,
    enabled, remark, creator, updater, create_time, update_time, deleted
) VALUES
(
    'AGV-MOCK-01',
    'AGV_MOCK',
    'EXCLUSIVE',
    'ZONE-A',
    1,
    b'1',
    'AGV mock 独占资源。',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'POST-PROCESSOR-FLOW-MOCK-01',
    'POST_PROCESSOR_FLOW_MOCK',
    'EXCLUSIVE',
    'ZONE-A',
    1,
    b'1',
    '后处理机台 mock 独占资源。',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
);

-- ------------------------------------------------------------------
-- 3. 步骤定义
-- ------------------------------------------------------------------

DELETE FROM pd_pipeline_step WHERE pipeline_key = 'post_processor_event_batch_mock';
DELETE FROM pd_pipeline_definition WHERE pipeline_key = 'post_processor_event_batch_mock';
DELETE FROM pd_step_definition WHERE step_key IN (
    'pp_bind_batch_samples',
    'pp_query_loaded_carrier_location',
    'pp_agv_move_to_processor',
    'pp_start_processor_task',
    'pp_wait_machine_event',
    'pp_route_machine_event',
    'pp_mark_scan_failed_sample',
    'pp_check_required_materials',
    'pp_route_material_enough',
    'pp_query_replenish_material_location',
    'pp_agv_replenish_material',
    'pp_notify_material_ready',
    'pp_recheck_required_materials',
    'pp_route_material_recheck',
    'pp_wait_experiment_result',
    'pp_save_experiment_result',
    'pp_mark_material_failed'
);

INSERT INTO pd_step_definition (
    step_key, version, name, description, step_type,
    device_type, command, executor, bean_name, method_name, chain_id,
    default_params, params_schema, output_fields,
    default_timeout_ms, default_max_attempts, default_backoff_ms,
    compensate_step_key, compensate_params,
    runnable_standalone, mock_output, status,
    creator, updater, create_time, update_time, deleted
) VALUES
(
    'pp_bind_batch_samples',
    1,
    '绑定4个样本与载具',
    '建立批次、载具、孔位、样本之间的关系。',
    'COMPUTE',
    NULL,
    NULL,
    'BEAN',
    NULL,
    NULL,
    NULL,
    '{}',
    NULL,
    '["batchId","carrierId","sampleInfos","sampleCount"]',
    10000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    '{"batchId":"BATCH-PP-001","carrierId":"CARRIER-PP-001","sampleCount":4,"sampleInfos":[{"sampleId":"SAMPLE-001","hole":1},{"sampleId":"SAMPLE-002","hole":2},{"sampleId":"SAMPLE-003","hole":3},{"sampleId":"SAMPLE-004","hole":4}]}',
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_query_loaded_carrier_location',
    1,
    '查询载具当前位置',
    'AGV 搬运前先查询载具/物料所在库位，并组装 AGV command。',
    'COMPUTE',
    NULL,
    NULL,
    'BEAN',
    NULL,
    NULL,
    NULL,
    '{}',
    NULL,
    '["sourceArea","sourcePos","targetStation","agvCommand"]',
    10000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    '{"sourceArea":"A","sourcePos":"1","targetStation":"POST_PROCESSOR_01","agvCommand":[{"step":"step1","taskName":"取载具到AGV","sourceArea":"A","sourcePos":"1","agvArea":"B","agvPos":"2","sourceStartPos":"1","count":"1","destinationStartPos":"1"},{"step":"step2","taskName":"AGV移动","agvStationName":"POST_PROCESSOR_01"},{"step":"step3","taskName":"从AGV放到后处理机台","agvArea":"B","agvPos":"2","desArea":"POST_PROCESSOR","desPos":"1","sourceStartPos":"1","count":"1","destinationStartPos":"1"}]}',
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_agv_move_to_processor',
    1,
    'AGV搬运到后处理机台',
    '使用查询到的载具位置组装 AGV startTask。',
    'INSTRUMENT',
    'AGV_MOCK',
    'startTask',
    NULL,
    NULL,
    NULL,
    NULL,
    '{"disableSysFieldInjection":true}',
    NULL,
    '["deviceTaskId","deviceType","command"]',
    120000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    '{"deviceTaskId":"AGV-MOCK-TO-PP","deviceType":"AGV_MOCK","command":"startTask"}',
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_start_processor_task',
    1,
    '启动后处理机台任务',
    '下发任务后机台自行扫码，后续通过事件回调推进。',
    'INSTRUMENT',
    'POST_PROCESSOR_FLOW_MOCK',
    'startTask',
    NULL,
    NULL,
    NULL,
    NULL,
    '{"taskId":"${sys.executionId}_post_processor","carrierId":"${s_bind_samples.carrierId}","sampleInfos":"${s_bind_samples.sampleInfos}"}',
    NULL,
    '["deviceTaskId","deviceType","command"]',
    120000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    '{"deviceTaskId":"PP-MOCK-TASK","deviceType":"POST_PROCESSOR_FLOW_MOCK","command":"startTask"}',
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_wait_machine_event',
    1,
    '等待机台事件',
    '等待后处理机台回调 scanFailed/materialRequired/experimentFinished。',
    'WAIT',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{"waitReason":"等待后处理机台事件回调"}',
    NULL,
    '["eventType","sampleId","materials","sampleResults"]',
    86400000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    NULL,
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_route_machine_event',
    1,
    '机台事件分流',
    '根据机台回调事件类型路由。',
    'CONDITION',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    NULL,
    '["branchName","conditionResult"]',
    5000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    NULL,
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_mark_scan_failed_sample',
    1,
    '标记扫码失败样本',
    '将机台回调的扫码失败样本标记为失败，不主动触发扫码。',
    'COMPUTE',
    NULL,
    NULL,
    'BEAN',
    NULL,
    NULL,
    NULL,
    '{}',
    NULL,
    '["failedSampleId","validSampleCount"]',
    10000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    '{"failedSampleId":"SAMPLE-001","validSampleCount":3}',
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_check_required_materials',
    1,
    '校验机台请求物料',
    '根据机台请求的物料清单校验库存/库位是否满足。',
    'COMPUTE',
    NULL,
    NULL,
    'BEAN',
    NULL,
    NULL,
    NULL,
    '{}',
    NULL,
    '["materialEnough","missingMaterials","materials"]',
    10000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    '{"materialEnough":true,"missingMaterials":[],"materials":[{"materialCode":"SOLVENT_A","requiredVolume":1000,"sourceArea":"MAT","sourcePos":"1"}]}',
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_route_material_enough',
    1,
    '物料是否充足',
    '物料充足则继续等待实验结果，不足则进入补料。',
    'CONDITION',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    NULL,
    '["branchName","conditionResult"]',
    5000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    NULL,
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_query_replenish_material_location',
    1,
    '查询补料物料位置',
    '物料不足时查询缺料所在库位，并组装补料 AGV command。',
    'COMPUTE',
    NULL,
    NULL,
    'BEAN',
    NULL,
    NULL,
    NULL,
    '{}',
    NULL,
    '["agvCommand","materials"]',
    10000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    '{"materials":[{"materialCode":"SOLVENT_A","sourceArea":"MAT","sourcePos":"1"}],"agvCommand":[{"step":"step1","taskName":"取补料到AGV","sourceArea":"MAT","sourcePos":"1","agvArea":"B","agvPos":"2","sourceStartPos":"1","count":"1","destinationStartPos":"1"},{"step":"step2","taskName":"AGV移动","agvStationName":"POST_PROCESSOR_01"},{"step":"step3","taskName":"补料放到后处理机台","agvArea":"B","agvPos":"2","desArea":"POST_PROCESSOR","desPos":"MAT-INPUT","sourceStartPos":"1","count":"1","destinationStartPos":"1"}]}',
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_agv_replenish_material',
    1,
    'AGV补料到后处理机台',
    '根据缺料位置发起 AGV 补料任务。',
    'INSTRUMENT',
    'AGV_MOCK',
    'startTask',
    NULL,
    NULL,
    NULL,
    NULL,
    '{"disableSysFieldInjection":true}',
    NULL,
    '["deviceTaskId","deviceType","command"]',
    120000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    '{"deviceTaskId":"AGV-MOCK-REPLENISH","deviceType":"AGV_MOCK","command":"startTask"}',
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_notify_material_ready',
    1,
    '通知机台物料到位',
    '补料完成后通知后处理机台继续。',
    'INSTRUMENT',
    'POST_PROCESSOR_FLOW_MOCK',
    'materialReady',
    NULL,
    NULL,
    NULL,
    NULL,
    '{"taskId":"${input.taskId}"}',
    NULL,
    '["deviceTaskId","deviceType","command"]',
    30000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    '{"deviceTaskId":"PP-MATERIAL-READY","deviceType":"POST_PROCESSOR_FLOW_MOCK","command":"materialReady"}',
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_recheck_required_materials',
    1,
    '补料后复核物料',
    '补料后复核物料是否满足，mock 默认满足。',
    'COMPUTE',
    NULL,
    NULL,
    'BEAN',
    NULL,
    NULL,
    NULL,
    '{}',
    NULL,
    '["materialEnough","missingMaterials","materials"]',
    10000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    '{"materialEnough":true,"missingMaterials":[],"materials":[{"materialCode":"SOLVENT_A","requiredVolume":1000}]}',
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_route_material_recheck',
    1,
    '补料复核分流',
    '补料后仍不足则标记物料失败，满足则等待实验结果。',
    'CONDITION',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    NULL,
    '["branchName","conditionResult"]',
    5000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    NULL,
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_wait_experiment_result',
    1,
    '等待实验结果',
    '等待后处理机台最终实验结果回调。',
    'WAIT',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{"waitReason":"等待后处理机台实验结果回调"}',
    NULL,
    '["sampleResults","rawResult"]',
    86400000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    NULL,
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_save_experiment_result',
    1,
    '保存实验结果',
    '保存机台回调的样本实验结果。',
    'COMPUTE',
    NULL,
    NULL,
    'BEAN',
    NULL,
    NULL,
    NULL,
    '{}',
    NULL,
    '["saved","resultCount"]',
    10000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    '{"saved":true,"resultCount":4}',
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
),
(
    'pp_mark_material_failed',
    1,
    '标记物料不足失败',
    '补料后仍然不足时标记流程物料失败。',
    'COMPUTE',
    NULL,
    NULL,
    'BEAN',
    NULL,
    NULL,
    NULL,
    '{}',
    NULL,
    '["failed","reason"]',
    10000,
    1,
    2000,
    NULL,
    NULL,
    b'1',
    '{"failed":true,"reason":"MATERIAL_NOT_ENOUGH_AFTER_REPLENISH"}',
    'ACTIVE',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
);

-- ------------------------------------------------------------------
-- 4. 流程定义
-- ------------------------------------------------------------------

INSERT INTO pd_pipeline_definition (
    pipeline_key, version, name, description,
    fail_strategy, compensate_strategy,
    default_timeout_ms, default_max_attempts, default_backoff_ms,
    default_input_params, status, published_at,
    sample_mode, sample_bind_nodes,
    creator, updater, create_time, update_time, deleted
) VALUES (
    'post_processor_event_batch_mock',
    1,
    '后处理机台事件驱动批处理流程Mock',
    '绑定样本、查询载具位置、AGV搬运、启动机台、等待机台扫码/物料/结果事件，支持物料不足时 AGV 补料。',
    'FAIL_FAST',
    'NONE',
    1800000,
    1,
    2000,
    '{"taskId":"PP-TASK-20260707-001","carrierId":"CARRIER-PP-001","sampleInfos":[{"sampleId":"SAMPLE-001","hole":1},{"sampleId":"SAMPLE-002","hole":2},{"sampleId":"SAMPLE-003","hole":3},{"sampleId":"SAMPLE-004","hole":4}]}',
    'ACTIVE',
    NOW(3),
    'OPTIONAL',
    '["s_bind_samples"]',
    'admin',
    'admin',
    NOW(3),
    NOW(3),
    b'0'
);

-- ------------------------------------------------------------------
-- 5. 流程节点 DAG
-- ------------------------------------------------------------------

INSERT INTO pd_pipeline_step (
    pipeline_key, pipeline_version, node_id,
    dispatch_mode, step_key, step_type, step_version, task_type,
    depends_on, condition_expr, true_branch, false_branch, branches,
    params_override, input_mapping, output_mapping,
    timeout_ms, max_attempts, backoff_ms, on_failure,
    compensate_node_id, compensate_step_key, compensate_params, compensate_on,
    command, runnable_standalone, mock_output, sort_order, ui_position,
    resource_enabled, zone_code, resource_wait_timeout_ms,
    creator, updater, create_time, update_time, deleted
) VALUES
(
    'post_processor_event_batch_mock', 1, 's_bind_samples',
    'DIRECT', 'pp_bind_batch_samples', 'COMPUTE', 1, NULL,
    NULL, NULL, NULL, NULL, NULL,
    '{}', NULL, NULL,
    10000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 1, '{"x":80,"y":100}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_query_loaded_carrier_location',
    'DIRECT', 'pp_query_loaded_carrier_location', 'COMPUTE', 1, NULL,
    '["s_bind_samples"]', NULL, NULL, NULL, NULL,
    '{}', '{"carrierId":"${s_bind_samples.carrierId}"}', NULL,
    10000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 2, '{"x":320,"y":100}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_agv_to_post_processor',
    'DIRECT', 'pp_agv_move_to_processor', 'INSTRUMENT', 1, NULL,
    '["s_query_loaded_carrier_location"]', NULL, NULL, NULL, NULL,
    '{}',
    '{"taskId":"${input.taskId}","command":"${s_query_loaded_carrier_location.agvCommand}"}',
    NULL,
    120000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 3, '{"x":600,"y":100}',
    b'1', 'ZONE-A', 300000,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_start_post_processor_task',
    'DIRECT', 'pp_start_processor_task', 'INSTRUMENT', 1, NULL,
    '["s_agv_to_post_processor"]', NULL, NULL, NULL, NULL,
    '{}',
    '{"taskId":"${input.taskId}","carrierId":"${s_bind_samples.carrierId}","sampleInfos":"${s_bind_samples.sampleInfos}"}',
    NULL,
    120000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 4, '{"x":880,"y":100}',
    b'1', 'ZONE-A', 300000,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_wait_machine_event',
    'DIRECT', 'pp_wait_machine_event', 'WAIT', 1, NULL,
    '["s_start_post_processor_task"]', NULL, NULL, NULL, NULL,
    '{}', NULL, NULL,
    86400000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 5, '{"x":1160,"y":100}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_route_machine_event',
    'DIRECT', 'pp_route_machine_event', 'CONDITION', 1, NULL,
    '["s_wait_machine_event"]', 'eventType', NULL, NULL,
    '{"scanFailed":"s_mark_scan_failed_sample","materialRequired":"s_check_required_materials","experimentFinished":"s_save_experiment_result_direct"}',
    '{}',
    '{"eventType":"${s_wait_machine_event.eventType}"}',
    NULL,
    5000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 6, '{"x":1420,"y":100}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_mark_scan_failed_sample',
    'DIRECT', 'pp_mark_scan_failed_sample', 'COMPUTE', 1, NULL,
    '["s_route_machine_event"]', NULL, NULL, NULL, NULL,
    '{}',
    '{"sampleId":"${s_wait_machine_event.sampleId}","reason":"${s_wait_machine_event.reason}"}',
    NULL,
    10000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 7, '{"x":1680,"y":20}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_check_required_materials',
    'DIRECT', 'pp_check_required_materials', 'COMPUTE', 1, NULL,
    '["s_route_machine_event"]', NULL, NULL, NULL, NULL,
    '{}',
    '{"materials":"${s_wait_machine_event.materials}"}',
    NULL,
    10000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 8, '{"x":1680,"y":180}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_route_material_enough',
    'DIRECT', 'pp_route_material_enough', 'CONDITION', 1, NULL,
    '["s_check_required_materials"]', 'materialEnough ? ''enough'' : ''insufficient''', NULL, NULL,
    '{"enough":"s_wait_experiment_result","insufficient":"s_query_replenish_material_location"}',
    '{}',
    '{"materialEnough":"${s_check_required_materials.materialEnough}"}',
    NULL,
    5000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 9, '{"x":1940,"y":180}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_query_replenish_material_location',
    'DIRECT', 'pp_query_replenish_material_location', 'COMPUTE', 1, NULL,
    '["s_route_material_enough"]', NULL, NULL, NULL, NULL,
    '{}',
    '{"missingMaterials":"${s_check_required_materials.missingMaterials}"}',
    NULL,
    10000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 10, '{"x":2200,"y":300}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_agv_replenish_material',
    'DIRECT', 'pp_agv_replenish_material', 'INSTRUMENT', 1, NULL,
    '["s_query_replenish_material_location"]', NULL, NULL, NULL, NULL,
    '{}',
    '{"taskId":"${input.taskId}_replenish","command":"${s_query_replenish_material_location.agvCommand}"}',
    NULL,
    120000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 11, '{"x":2460,"y":300}',
    b'1', 'ZONE-A', 300000,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_notify_material_ready',
    'DIRECT', 'pp_notify_material_ready', 'INSTRUMENT', 1, NULL,
    '["s_agv_replenish_material"]', NULL, NULL, NULL, NULL,
    '{}',
    '{"taskId":"${input.taskId}","materials":"${s_query_replenish_material_location.materials}"}',
    NULL,
    30000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 12, '{"x":2720,"y":300}',
    b'1', 'ZONE-A', 300000,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_recheck_required_materials',
    'DIRECT', 'pp_recheck_required_materials', 'COMPUTE', 1, NULL,
    '["s_notify_material_ready"]', NULL, NULL, NULL, NULL,
    '{}', NULL, NULL,
    10000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 13, '{"x":2980,"y":300}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_route_material_recheck',
    'DIRECT', 'pp_route_material_recheck', 'CONDITION', 1, NULL,
    '["s_recheck_required_materials"]', 'materialEnough ? ''enough'' : ''insufficient''', NULL, NULL,
    '{"enough":"s_wait_experiment_result_after_replenish","insufficient":"s_mark_material_failed"}',
    '{}',
    '{"materialEnough":"${s_recheck_required_materials.materialEnough}"}',
    NULL,
    5000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 14, '{"x":3240,"y":300}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_wait_experiment_result',
    'DIRECT', 'pp_wait_experiment_result', 'WAIT', 1, NULL,
    '["s_route_material_enough"]', NULL, NULL, NULL, NULL,
    '{}', NULL, NULL,
    86400000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 15, '{"x":3500,"y":180}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_save_experiment_result_after_material',
    'DIRECT', 'pp_save_experiment_result', 'COMPUTE', 1, NULL,
    '["s_wait_experiment_result"]', NULL, NULL, NULL, NULL,
    '{}',
    '{"sampleResults":"${s_wait_experiment_result.sampleResults}"}',
    NULL,
    10000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 16, '{"x":3760,"y":180}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_wait_experiment_result_after_replenish',
    'DIRECT', 'pp_wait_experiment_result', 'WAIT', 1, NULL,
    '["s_route_material_recheck"]', NULL, NULL, NULL, NULL,
    '{}', NULL, NULL,
    86400000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 16, '{"x":3500,"y":300}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_save_experiment_result_after_replenish',
    'DIRECT', 'pp_save_experiment_result', 'COMPUTE', 1, NULL,
    '["s_wait_experiment_result_after_replenish"]', NULL, NULL, NULL, NULL,
    '{}',
    '{"sampleResults":"${s_wait_experiment_result_after_replenish.sampleResults}"}',
    NULL,
    10000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 17, '{"x":3760,"y":300}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_save_experiment_result_direct',
    'DIRECT', 'pp_save_experiment_result', 'COMPUTE', 1, NULL,
    '["s_route_machine_event"]', NULL, NULL, NULL, NULL,
    '{}',
    '{"sampleResults":"${s_wait_machine_event.sampleResults}"}',
    NULL,
    10000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 18, '{"x":1680,"y":420}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
),
(
    'post_processor_event_batch_mock', 1, 's_mark_material_failed',
    'DIRECT', 'pp_mark_material_failed', 'COMPUTE', 1, NULL,
    '["s_route_material_recheck"]', NULL, NULL, NULL, NULL,
    '{}',
    '{"missingMaterials":"${s_recheck_required_materials.missingMaterials}"}',
    NULL,
    10000, 1, 2000, 'FAIL_PIPELINE',
    NULL, NULL, NULL, NULL,
    NULL, b'1', NULL, 19, '{"x":3500,"y":420}',
    b'0', NULL, NULL,
    'admin', 'admin', NOW(3), NOW(3), b'0'
);
